### ISSUE TITLE
安装时出现错误

### ISSUE THREAD

**Issue by SiliCAT** [sensec/ddns-scripts_aliyun#1]
`root@OpenWrt:~# opkg install ddns-scripts_aliyun_1.0.0-1_all.ipk
Installing ddns-scripts_aliyun (1.0.0-1) to root...
Configuring ddns-scripts_aliyun.
//usr/lib/opkg/info/ddns-scripts_aliyun.postinst: /usr/lib/opkg/info/ddns-scripts_aliyun.postinst-pkg: line 6: can't create /etc/ddns/services: nonexistent directory
//usr/lib/opkg/info/ddns-scripts_aliyun.postinst: /usr/lib/opkg/info/ddns-scripts_aliyun.postinst-pkg: line 7: can't create /etc/ddns/services_ipv6: nonexistent directory
`

DDNS服务提供商一栏中也找不到aliyun.com

ddns-scripts wget openssl-util luci-app-ddns
都已安装

**Comment by sensec** [comment]
/etc/ddns/services文件不存在，原因是ddns-scripts 未安装或版本太旧。已在恩山论坛回复。
